_hitbox = instance_create_depth(x, y, -1, obj_hitbox);
_hitbox.owner = id;
_hitbox.image_xscale = argument0;
_hitbox.image_yscale = argument1;
_hitbox.x_offset = argument2;
_hitbox.y_offset = argument3;
_hitbox.duration = argument4;
_hitbox.knockback_x_hit = argument5;
_hitbox.knockback_y_hit = argument6;
_hitbox.hit_stun = argument7;
return _hitbox;